# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InspeeroLibDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InspeeroLibDemo
	
#   pod 'InspeeroLibs/InAppPurchase',:path=>'/Users/bhaveshsarwar/Documents/Inspeero/iOS_Projects/InspeeroLibraries'

  target 'InspeeroLibDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InspeeroLibDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
